apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "shaarli.fullname" . }}
  labels:
    app: {{ template "shaarli.name" . }}
    chart: {{ template "shaarli.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "shaarli.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "shaarli.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.populate }}
      initContainers:
        - name: populate
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          args:
          - sh
          - /opt/scripts/populate.sh
          {{- if .material.enabled }}
          - /opt/scripts/material.sh
          {{- end }}
          volumeMounts:
          - name: data
            mountPath: /var/www/shaarli/data
          - name: scripts
            mountPath: /opt/scripts
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # TODO
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - name: data
            mountPath: /var/www/shaarli/data
          {{- with .Values.populate.material }}
          {{- if .enabled }}
          - name: data
            mountPath: /var/www/shaarli/tpl/material
            subPath: {{ printf .source.dir .version }}
          {{- end }}
          {{- end }}
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "shaarli.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: scripts
        configMap:
          name: {{ template "shaarli.fullname" . }}
          items:
          {{- with .Values.populate.material }}
          - key: material.sh
            path: material.sh
          {{- end }}
          - key: populate.sh
            path: populate.sh
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
